// Map of city names to IATA codes
export const cityToIata = {
  // India
  'mumbai': 'BOM',
  'delhi': 'DEL',
  'bangalore': 'BLR',
  'hyderabad': 'HYD',
  'ahmedabad': 'AMD',
  'chennai': 'MAA',
  'kolkata': 'CCU',
  'surat': 'STV',
  'pune': 'PNQ',
  'jaipur': 'JAI',
  'lucknow': 'LKO',
  'goa': 'GOI',
  'kochi': 'COK',
  'coimbatore': 'CJB',
  'vadodara': 'BDQ',
  'indore': 'IDR',
  'nagpur': 'NAG',
  'kozhikode': 'CCJ',
  'visakhapatnam': 'VTZ',
  'bhopal': 'BHO',
  'patna': 'PAT',
  'guwahati': 'GAU',
  'chandigarh': 'IXC',
  'amritsar': 'ATQ',
  'varanasi': 'VNS',
  'mangalore': 'IXE',
  'srinagar': 'SXR',
  'jammu': 'IXJ',
  'leh': 'IXL',
  'shimla': 'SLV',
  'dharamshala': 'DHM',
  'dehradun': 'DED',
  'udaipur': 'UDR',
  'jodhpur': 'JDH',
  'jaisalmer': 'JSA',
  'jabalpur': 'JLR',
  'gwalior': 'GWL',
  'bikaner': 'BKB',
  'raipur': 'RPR',
  'bhubaneswar': 'BBI',
  'tiruchirappalli': 'TRZ',
  'madurai': 'IXM',
  'cochin': 'COK',
  'trivandrum': 'TRV',
  'goa': 'GOI',
  'puducherry': 'PNY',
  'shillong': 'SHL',
  'imphal': 'IMF',
  'aizawl': 'AJL',
  'dimapur': 'DMU',
  'kohima': 'KHU',
  'itanagar': 'HGI',
  'gangtok': 'PYG',
  'port blair': 'IXZ',
  'kavaratti': 'KVA',
  'leh': 'IXL',
  'srinagar': 'SXR',
  'jammu': 'IXJ',
  'amritsar': 'ATQ',
  'chandigarh': 'IXC',
  'dehradun': 'DED',
  'shimla': 'SLV',
  'dharamshala': 'DHM',
  'manali': 'KUU',
  'mcleodganj': 'DHM',
  'dalhousie': 'DHM',
  'kullu': 'KUU',
  'shimla': 'SLV',
  'nainital': 'PGH',
  'ranikhet': 'PGH',
  'mussourie': 'DED',
  'rishikesh': 'DED',
  'haridwar': 'DED',
  'ayodhya': 'AYJ',
  'varanasi': 'VNS',
  'allahabad': 'IXD',
  'lucknow': 'LKO',
  'kanpur': 'KNU',
  'agra': 'AGR',
  'jhansi': 'JHS',
  'gwalior': 'GWL',
  'khajuraho': 'HJR',
  'bandhavgarh': 'JHS',
  'kanha': 'NAH',
  'panna': 'NYN',
  'pachmarhi': 'NYN',
  'bhopal': 'BHO',
  'indore': 'IDR',
  'ujjain': 'UJJ',
  'omkareshwar': 'IDR',
  'maheshwar': 'IDR',
  'mahabalipuram': 'MAA',
  'pondicherry': 'PNY',
  'chidambaram': 'CDP',
  'tiruvannamalai': 'TJV',
  'kanchipuram': 'MAA',
  'mamallapuram': 'MAA',
  'tanjore': 'TJV',
  'trichy': 'TRZ',
  'madurai': 'IXM',
  'rameshwaram': 'RMD',
  'kanyakumari': 'TRV',
  'kovalam': 'TRV',
  'varkala': 'TRV',
  'alleppey': 'TRV',
  'kumarakom': 'COK',
  'munnar': 'COK',
  'thekkady': 'COK',
  'wayanad': 'CCJ',
  'coorg': 'MYQ',
  'mysore': 'MYQ',
  'hampi': 'BLR',
  'badami': 'BLR',
  'pattadakal': 'BLR',
  'bijapur': 'BLR',
  'halebidu': 'MYQ',
  'belur': 'MYQ',
  'shravanabelagola': 'MYQ',
  'coorg': 'MYQ',
  'chikmagalur': 'MYQ',
  'mahabaleshwar': 'BOM',
  'lonavala': 'PNQ',
  'matheran': 'BOM',
  'alibaug': 'BOM',
  'mahabaleshwar': 'BOM',
  'lonavala': 'PNQ',
  'matheran': 'BOM',
  'alibaug': 'BOM',
  'mahabaleshwar': 'BOM',
  'lonavala': 'PNQ',
  'matheran': 'BOM',
  'alibaug': 'BOM',
  'mahabaleshwar': 'BOM',
  'lonavala': 'PNQ',
  'matheran': 'BOM',
  'alibaug': 'BOM',
  'mahabaleshwar': 'BOM',
  'lonavala': 'PNQ',
  'matheran': 'BOM',
  'alibaug': 'BOM',
  'mahabaleshwar': 'BOM',
  'lonavala': 'PNQ',
  'matheran': 'BOM',
  'alibaug': 'BOM',
  'mahabaleshwar': 'BOM',
  'lonavala': 'PNQ',
  'matheran': 'BOM',
  'alibaug': 'BOM',
  'mahabaleshwar': 'BOM',
  'lonavala': 'PNQ',
  'matheran': 'BOM',
  'alibaug': 'BOM',
  // Add more cities as needed
};

// Function to get IATA code for a city name
export const getIataCode = (cityName) => {
  if (!cityName) return '';
  const trimmed = cityName.trim();

  // If the user already entered a 3-letter code, accept it directly
  if (/^[A-Za-z]{3}$/.test(trimmed)) {
    return trimmed.toUpperCase();
  }

  const cityKey = trimmed.toLowerCase().split(',')[0].trim();
  return cityToIata[cityKey] || '';
};

// Function to get city name from IATA code
export const getCityFromIata = (iataCode) => {
  if (!iataCode) return '';
  const entry = Object.entries(cityToIata).find(([_, code]) => code === iataCode);
  return entry ? entry[0].charAt(0).toUpperCase() + entry[0].slice(1) : iataCode;
};
